language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r todo ./*
  - mkdir -p deploy
  - mv todo.zip deploy/todo.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jinia-todo-app
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jinia-todo-app
    key: todo.zip
    bundle_type: zip
    application: todoapp
    deployment_group: todo-app
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true


## CI 실행 완료 시 메일로 알람
#notifications:
#  email:
#    recipients:
#      - creee77@gmail.com
#
