spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/todotest;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

auth:
  key: 123
